### ISSUE TITLE
TypeError: cannot create property 'data' on transient object

### ISSUE THREAD

**Issue by nick-s-b** [zxhzxhz/mpv-chapters#1]
Hi,

I just installed `mpv-chapters` and I'm getting this error:

````
$ mpv rendered.mp4
convert_script: The 'tick' event is deprecated and will be removed.
   cplayer: Resuming playback. This behavior can be disabled with --no-resume-playback.
   cplayer:  (+) Video --vid=1 (*) (h264 1280x720 23.976fps)
   cplayer:  (+) Audio --aid=1 (*) (aac 2ch 48000Hz)
display-tags: File tags:
display-tags:  Title: rendition
   cplayer: AO: [alsa] 48000Hz stereo 2ch float
mpv_chapters: TypeError: cannot create property 'data' on transient object
mpv_chapters: 	at /home/user/.config/mpv/scripts/mpv_chapters.js:103
mpv_chapters: 	at Array.prototype.forEach (native)
mpv_chapters: 	at drawChapterList (/home/user/.config/mpv/scripts/mpv_chapters.js:94)
mpv_chapters: 	at init (/home/user/.config/mpv/scripts/mpv_chapters.js:33)
mpv_chapters: 	at dispatch_event (@/defaults.js:52)
mpv_chapters: 	at mp_event_loop (@/defaults.js:750)
mpv_chapters: 	at run_script (native)
mpv_chapters: Could not load javascript /home/user/.config/mpv/scripts/mpv_chapters.js
   cplayer: VO: [gpu] 1280x720 yuv420p
statusline: (Paused) AV: 00:00:01 / 03:04:00 (0%) A-V:  0.000
[+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------]
   cplayer: Saving state.
   cplayer: 
   cplayer: Exiting... (Quit)
````

I'm running Linux and `mpv` is freshly compiled and it includes JavaScript support:
````
$ uname -a
Linux forethought 5.12.15-arch1-1 #1 SMP PREEMPT Wed, 07 Jul 2021 23:35:29 +0000 x86_64 GNU/Linux

$ mpv
   cplayer: mpv 0.33.0-228-g1e90ec647c Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
   cplayer:  built on Fri Jul 16 23:06:10 EDT 2021
   cplayer: FFmpeg library versions:
   cplayer:    libavutil       56.70.100
   cplayer:    libavcodec      58.134.100
   cplayer:    libavformat     58.76.100
   cplayer:    libswscale      5.9.100
   cplayer:    libavfilter     7.110.100
   cplayer:    libswresample   3.9.100
   cplayer: FFmpeg version: n4.4


$ mpv -v | grep javascript
[cplayer] List of enabled features: 52arch alsa asm build-date caca cplayer cplugins debug-build drm dvbin egl egl-drm egl-helpers egl-x11 ffmpeg gbm gbm.h gl gl-wayland glibc-thread-name glob glob-posix gpl iconv jack javascript jpeg lcms2 libarchive libass libavdevice libbluray libdl libm libmpv-shared libplacebo librt linux-fstatfs linux-input-event-codes lua memfd_create optimize plain-gl posix posix-or-mingw pthreads pulse rubberband shaderc shaderc-shared stdatomic uchardet vaapi vaapi-drm vaapi-egl vaapi-vulkan vaapi-wayland vaapi-x-egl vaapi-x11 vdpau vector vt.h vulkan wayland wayland-protocols x11 xv zimg zlib

````

When I press `Tab`, I don't see chapters. Any idea what could be wrong? Thanks.

**Comment by zxhzxhz** [comment]
> Hi,
> 
> I just installed `mpv-chapters` and I'm getting this error:
> 
> ```
> $ mpv rendered.mp4
> convert_script: The 'tick' event is deprecated and will be removed.
>    cplayer: Resuming playback. This behavior can be disabled with --no-resume-playback.
>    cplayer:  (+) Video --vid=1 (*) (h264 1280x720 23.976fps)
>    cplayer:  (+) Audio --aid=1 (*) (aac 2ch 48000Hz)
> display-tags: File tags:
> display-tags:  Title: rendition
>    cplayer: AO: [alsa] 48000Hz stereo 2ch float
> mpv_chapters: TypeError: cannot create property 'data' on transient object
> mpv_chapters: 	at /home/user/.config/mpv/scripts/mpv_chapters.js:103
> mpv_chapters: 	at Array.prototype.forEach (native)
> mpv_chapters: 	at drawChapterList (/home/user/.config/mpv/scripts/mpv_chapters.js:94)
> mpv_chapters: 	at init (/home/user/.config/mpv/scripts/mpv_chapters.js:33)
> mpv_chapters: 	at dispatch_event (@/defaults.js:52)
> mpv_chapters: 	at mp_event_loop (@/defaults.js:750)
> mpv_chapters: 	at run_script (native)
> mpv_chapters: Could not load javascript /home/user/.config/mpv/scripts/mpv_chapters.js
>    cplayer: VO: [gpu] 1280x720 yuv420p
> statusline: (Paused) AV: 00:00:01 / 03:04:00 (0%) A-V:  0.000
> [+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------]
>    cplayer: Saving state.
>    cplayer: 
>    cplayer: Exiting... (Quit)
> ```
> 
> I'm running Linux and `mpv` is freshly compiled and it includes JavaScript support:
> 
> ```
> $ uname -a
> Linux forethought 5.12.15-arch1-1 #1 SMP PREEMPT Wed, 07 Jul 2021 23:35:29 +0000 x86_64 GNU/Linux
> 
> $ mpv
>    cplayer: mpv 0.33.0-228-g1e90ec647c Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
>    cplayer:  built on Fri Jul 16 23:06:10 EDT 2021
>    cplayer: FFmpeg library versions:
>    cplayer:    libavutil       56.70.100
>    cplayer:    libavcodec      58.134.100
>    cplayer:    libavformat     58.76.100
>    cplayer:    libswscale      5.9.100
>    cplayer:    libavfilter     7.110.100
>    cplayer:    libswresample   3.9.100
>    cplayer: FFmpeg version: n4.4
> 
> 
> $ mpv -v | grep javascript
> [cplayer] List of enabled features: 52arch alsa asm build-date caca cplayer cplugins debug-build drm dvbin egl egl-drm egl-helpers egl-x11 ffmpeg gbm gbm.h gl gl-wayland glibc-thread-name glob glob-posix gpl iconv jack javascript jpeg lcms2 libarchive libass libavdevice libbluray libdl libm libmpv-shared libplacebo librt linux-fstatfs linux-input-event-codes lua memfd_create optimize plain-gl posix posix-or-mingw pthreads pulse rubberband shaderc shaderc-shared stdatomic uchardet vaapi vaapi-drm vaapi-egl vaapi-vulkan vaapi-wayland vaapi-x-egl vaapi-x11 vdpau vector vt.h vulkan wayland wayland-protocols x11 xv zimg zlib
> ```
> 
> When I press `Tab`, I don't see chapters. Any idea what could be wrong? Thanks.

I just pushed a new update, download and try again?

**Comment by nick-s-b** [comment]
@zxhzxhz thank you! Works perfectly now!
