### ISSUE TITLE
Mismatch chapters on "mpv-chapters" (reason: "mpv_sponsorblock")

### ISSUE THREAD

**Issue by Obegg** [zxhzxhz/mpv-chapters#2]
Using "mpv-chapters" = No issues.
Using "mpv-chapters" + "[mpv_sponsorblock](https://github.com/po5/mpv_sponsorblock)" = Mismatch chapters on "mpv-chapters".

"mpv_sponsorblock" = mpv script to skip sponsored segments of YouTube videos.
"mpv_sponsorblock" creates more chapters that interfere with "mpv-chapters".

Example of the issue:
This [YouTube Video](https://www.youtube.com/watch?v=8T3SLSfauAI):
Selecting chapter "Weapon Drills" will result jump to chapter "RTX 2060".

**Comment by zxhzxhz** [comment]
I've made an update which could possibly fix it, download mpv_chapters.js from **mpv_sponsorblock-fix-1 branch** and try again.
 ps: I didn't test the script with mpv_sponsorblock since I don't have python installed, please test and tell me if it works.

**Comment by Obegg** [comment]
@zxhzxhz
Thank you for trying to fix this issue, as a user of your script, I appreciate it!
As you instructed me, I tested the [fix](https://raw.githubusercontent.com/zxhzxhz/mpv-chapters/mpv_sponsorblock-fix-1/mpv_chapters.js) and my result was the same, It did not fix the issue.
You said you didn't test the fix with mpv_sponsorblock, because you don't have python installed, I can help you with that if you want me to ([at first it was complicated to me](https://github.com/po5/mpv_sponsorblock/issues/38))

**Comment by zxhzxhz** [comment]
> @zxhzxhz
> Thank you for trying to fix this issue, as a user of your script, I appreciate it!
> As you instructed me, I tested the [fix](https://raw.githubusercontent.com/zxhzxhz/mpv-chapters/mpv_sponsorblock-fix-1/mpv_chapters.js) and my result was the same, It did not fix the issue.

OK，I’ll try to make another fix later today

**Comment by Obegg** [comment]
> > @zxhzxhz
> > Thank you for trying to fix this issue, as a user of your script, I appreciate it!
> > As you instructed me, I tested the [fix](https://raw.githubusercontent.com/zxhzxhz/mpv-chapters/mpv_sponsorblock-fix-1/mpv_chapters.js) and my result was the same, It did not fix the issue.
> 
> OK，I’ll try to make another fix later today

Thank you!
Keep me updated, I will test the new fix.

**Comment by zxhzxhz** [comment]
fixed

**Comment by Obegg** [comment]
Can confirm it is fixed now, thank you!
Hopefully, it will be added to the main branch.
